import Head from 'next/head'

import Categories from '@features/Categories'
import Mockups from '@features/Mockups'

import { initializeStore } from '@store/index'
import { setActiveCategory } from '@store/categories/actions'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Smartmockups assignment</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Categories/>
        <Mockups/>
      </main>
    </div>
  )
}

export function getServerSideProps({ query }) {
  const { filter } = query
  const reduxStore = initializeStore()
  const { dispatch } = reduxStore

  if (filter) {
    dispatch(setActiveCategory(decodeURIComponent(filter)))
  }

  return { props: { initialReduxState: reduxStore.getState() } }
}